pool:
  vmImage: windows-latest
  
variables:
  BuildConfiguration: Release
  TestProjects: test/**/*.[Tt]ests.csproj
  PackProjects: src/IronVelocity.csproj

steps:
- task: DotNetCoreCLI@2 
  displayName: Build
  inputs:
    command: build
    arguments: --configuration $(BuildConfiguration)

- task: DotNetCoreCLI@2 
  displayName: Test
  inputs:
    command: test
    nobuild: true
    projects: $(TestProjects)
    arguments: --configuration $(BuildConfiguration)

- task: DotNetCoreCLI@2 
  displayName: Package
  inputs:
    command: pack
    nobuild: true
    packDirectory: $BUILD_ARTIFACTSTAGINGDIRECTORY
    packagesToPack: $(PackProjects)
    arguments: --configuration $(BuildConfiguration)
