namespace IronVelocity.Compilation.AST
{
    public enum VelocityExpressionType
    {
		Binary,
		CoerceToBoolean,
        CustomDirective,
        Dictionary,
        DictionaryString,
        Directive,
        Foreach,
        GlobalVariable,
        IndexInvocation,
        IntegerRange,
        InterpolatedString,
        MethodInvocation,
        ObjectArray,
        PropertyAccess,
        Reference,
        RenderableExpression,
        RenderedBlock,
        SetDirective,
        SetMember,
        SetIndex,
        TemplatedForeach,
        TemporaryVariableScope,
        Variable,
        DirectiveWord
    }
}
